# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackctl < Formula
  desc "CLI for managing Kubernetes stack deployments via k8s-stack-manager"
  homepage "https://github.com/omattsson/stackctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omattsson/stackctl/releases/download/v0.1.0/stackctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "193d0bd4536f96d16d5dc6f3d7038f9c9fe4a6cc09ced9dfba9f2ef7597ed097"

      def install
        bin.install "stackctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omattsson/stackctl/releases/download/v0.1.0/stackctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "e304b3cfa3001c3387f8b6917f0c847cacd73897f5bb11812ae8d6793628d951"

      def install
        bin.install "stackctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/omattsson/stackctl/releases/download/v0.1.0/stackctl_0.1.0_linux_amd64.tar.gz"
        sha256 "8054db67404680e96c8c69a56830bd49d4a76cf922f383f94ffb09cd46099843"

        def install
          bin.install "stackctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/omattsson/stackctl/releases/download/v0.1.0/stackctl_0.1.0_linux_arm64.tar.gz"
        sha256 "037c99c78fe51f10333f01df61d7d4d02f2c0552576523d4ca3d8fd284ffb1ab"

        def install
          bin.install "stackctl"
        end
      end
    end
  end

  test do
    system "#{bin}/stackctl", "version"
  end
end
