# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackctl < Formula
  desc "CLI for managing Kubernetes stack deployments via k8s-stack-manager"
  homepage "https://github.com/omattsson/stackctl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omattsson/stackctl/releases/download/v0.2.0/stackctl_0.2.0_darwin_amd64.tar.gz"
      sha256 "d6db3886292ee067e9d7807bcbd6b5b4deae324f20d69954335196bb64ea90a4"

      def install
        bin.install "stackctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omattsson/stackctl/releases/download/v0.2.0/stackctl_0.2.0_darwin_arm64.tar.gz"
      sha256 "7a346c3ff550dcf1abc282b8d8d906b9b1f27a8248d2ba317165e796b41aeb20"

      def install
        bin.install "stackctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/omattsson/stackctl/releases/download/v0.2.0/stackctl_0.2.0_linux_amd64.tar.gz"
        sha256 "73c43cd374adbe797b9d319799472d3355ec81ca831f57fc3f6d8d6890ed523b"

        def install
          bin.install "stackctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/omattsson/stackctl/releases/download/v0.2.0/stackctl_0.2.0_linux_arm64.tar.gz"
        sha256 "2eba4b7e3c4290a3e27da29f7539c7ce282b518212b81d83105b85c6d2bc5162"

        def install
          bin.install "stackctl"
        end
      end
    end
  end

  test do
    system "#{bin}/stackctl", "version"
  end
end
